options {
    directory "/var/cache/bind";
    listen-on { any; };
    allow-query { any; };
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    dnssec-validation no;
};

logging {
    channel query_log {
        stderr;
        severity info;
        print-time yes;
        print-category yes;
    };
    category queries { query_log; };
};

zone "." {
    type hint;
    file "/usr/share/dns/root.hints";
};
